name: mobmongo
description: Flutter MongoDB Plugin
version: 0.0.7
author: Aubrey Malabie <aubrey@aftarobot.com>
homepage: https://aftarbot.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.4+5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: com.aftarobot.mobmongo
    pluginClass: MobmongoPlugin
