name: mongodb_mobile
description: A new flutter plugin project.
version: 0.0.1
author: Aubrey Malabie
homepage: https://github.com/malengatiger/flutter-mongdb-mobile

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: com.example.mongodb_mobile
    pluginClass: MongodbMobilePlugin
